version: 2

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    goarm:
      - 5
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

upx:
  - enabled: true
    goos: [linux]
    compress: best
    lzma: true
    brute: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^typo:"
