// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sync

import (
	"github.com/lovelaze/nebula-sync/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// NewTarget creates a new instance of Target. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTarget(t interface {
	mock.TestingT
	Cleanup(func())
}) *Target {
	mock := &Target{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Target is an autogenerated mock type for the Target type
type Target struct {
	mock.Mock
}

type Target_Expecter struct {
	mock *mock.Mock
}

func (_m *Target) EXPECT() *Target_Expecter {
	return &Target_Expecter{mock: &_m.Mock}
}

// FullSync provides a mock function for the type Target
func (_mock *Target) FullSync(sync *config.Sync) error {
	ret := _mock.Called(sync)

	if len(ret) == 0 {
		panic("no return value specified for FullSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*config.Sync) error); ok {
		r0 = returnFunc(sync)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Target_FullSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullSync'
type Target_FullSync_Call struct {
	*mock.Call
}

// FullSync is a helper method to define mock.On call
//   - sync
func (_e *Target_Expecter) FullSync(sync interface{}) *Target_FullSync_Call {
	return &Target_FullSync_Call{Call: _e.mock.On("FullSync", sync)}
}

func (_c *Target_FullSync_Call) Run(run func(sync *config.Sync)) *Target_FullSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Sync))
	})
	return _c
}

func (_c *Target_FullSync_Call) Return(err error) *Target_FullSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Target_FullSync_Call) RunAndReturn(run func(sync *config.Sync) error) *Target_FullSync_Call {
	_c.Call.Return(run)
	return _c
}

// SelectiveSync provides a mock function for the type Target
func (_mock *Target) SelectiveSync(sync *config.Sync) error {
	ret := _mock.Called(sync)

	if len(ret) == 0 {
		panic("no return value specified for SelectiveSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*config.Sync) error); ok {
		r0 = returnFunc(sync)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Target_SelectiveSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectiveSync'
type Target_SelectiveSync_Call struct {
	*mock.Call
}

// SelectiveSync is a helper method to define mock.On call
//   - sync
func (_e *Target_Expecter) SelectiveSync(sync interface{}) *Target_SelectiveSync_Call {
	return &Target_SelectiveSync_Call{Call: _e.mock.On("SelectiveSync", sync)}
}

func (_c *Target_SelectiveSync_Call) Run(run func(sync *config.Sync)) *Target_SelectiveSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Sync))
	})
	return _c
}

func (_c *Target_SelectiveSync_Call) Return(err error) *Target_SelectiveSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Target_SelectiveSync_Call) RunAndReturn(run func(sync *config.Sync) error) *Target_SelectiveSync_Call {
	_c.Call.Return(run)
	return _c
}
