// Code generated by mockery v2.45.1. DO NOT EDIT.

package sync

import (
	config "github.com/lovelaze/nebula-sync/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// Target is an autogenerated mock type for the Target type
type Target struct {
	mock.Mock
}

type Target_Expecter struct {
	mock *mock.Mock
}

func (_m *Target) EXPECT() *Target_Expecter {
	return &Target_Expecter{mock: &_m.Mock}
}

// FullSync provides a mock function with given fields: _a0
func (_m *Target) FullSync(_a0 *config.Sync) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for FullSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Sync) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Target_FullSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullSync'
type Target_FullSync_Call struct {
	*mock.Call
}

// FullSync is a helper method to define mock.On call
//   - _a0 *config.Sync
func (_e *Target_Expecter) FullSync(_a0 interface{}) *Target_FullSync_Call {
	return &Target_FullSync_Call{Call: _e.mock.On("FullSync", _a0)}
}

func (_c *Target_FullSync_Call) Run(run func(_a0 *config.Sync)) *Target_FullSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Sync))
	})
	return _c
}

func (_c *Target_FullSync_Call) Return(_a0 error) *Target_FullSync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Target_FullSync_Call) RunAndReturn(run func(*config.Sync) error) *Target_FullSync_Call {
	_c.Call.Return(run)
	return _c
}

// ManualSync provides a mock function with given fields: _a0
func (_m *Target) ManualSync(_a0 *config.Sync) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ManualSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Sync) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Target_ManualSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManualSync'
type Target_ManualSync_Call struct {
	*mock.Call
}

// ManualSync is a helper method to define mock.On call
//   - _a0 *config.Sync
func (_e *Target_Expecter) ManualSync(_a0 interface{}) *Target_ManualSync_Call {
	return &Target_ManualSync_Call{Call: _e.mock.On("ManualSync", _a0)}
}

func (_c *Target_ManualSync_Call) Run(run func(_a0 *config.Sync)) *Target_ManualSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Sync))
	})
	return _c
}

func (_c *Target_ManualSync_Call) Return(_a0 error) *Target_ManualSync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Target_ManualSync_Call) RunAndReturn(run func(*config.Sync) error) *Target_ManualSync_Call {
	_c.Call.Return(run)
	return _c
}

// NewTarget creates a new instance of Target. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTarget(t interface {
	mock.TestingT
	Cleanup(func())
}) *Target {
	mock := &Target{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
