// Code generated by mockery v2.45.1. DO NOT EDIT.

package pihole

import (
	model "github.com/lovelaze/nebula-sync/internal/pihole/model"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ApiPath provides a mock function with given fields: target
func (_m *Client) ApiPath(target string) string {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for ApiPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Client_ApiPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApiPath'
type Client_ApiPath_Call struct {
	*mock.Call
}

// ApiPath is a helper method to define mock.On call
//   - target string
func (_e *Client_Expecter) ApiPath(target interface{}) *Client_ApiPath_Call {
	return &Client_ApiPath_Call{Call: _e.mock.On("ApiPath", target)}
}

func (_c *Client_ApiPath_Call) Run(run func(target string)) *Client_ApiPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_ApiPath_Call) Return(_a0 string) *Client_ApiPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_ApiPath_Call) RunAndReturn(run func(string) string) *Client_ApiPath_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields:
func (_m *Client) DeleteSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type Client_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
func (_e *Client_Expecter) DeleteSession() *Client_DeleteSession_Call {
	return &Client_DeleteSession_Call{Call: _e.mock.On("DeleteSession")}
}

func (_c *Client_DeleteSession_Call) Run(run func()) *Client_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_DeleteSession_Call) Return(_a0 error) *Client_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteSession_Call) RunAndReturn(run func() error) *Client_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function with given fields:
func (_m *Client) GetConfig() (*model.ConfigResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *model.ConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.ConfigResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.ConfigResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type Client_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *Client_Expecter) GetConfig() *Client_GetConfig_Call {
	return &Client_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *Client_GetConfig_Call) Run(run func()) *Client_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetConfig_Call) Return(configResponse *model.ConfigResponse, err error) *Client_GetConfig_Call {
	_c.Call.Return(configResponse, err)
	return _c
}

func (_c *Client_GetConfig_Call) RunAndReturn(run func() (*model.ConfigResponse, error)) *Client_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeleporter provides a mock function with given fields:
func (_m *Client) GetTeleporter() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTeleporter")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTeleporter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeleporter'
type Client_GetTeleporter_Call struct {
	*mock.Call
}

// GetTeleporter is a helper method to define mock.On call
func (_e *Client_Expecter) GetTeleporter() *Client_GetTeleporter_Call {
	return &Client_GetTeleporter_Call{Call: _e.mock.On("GetTeleporter")}
}

func (_c *Client_GetTeleporter_Call) Run(run func()) *Client_GetTeleporter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetTeleporter_Call) Return(_a0 []byte, _a1 error) *Client_GetTeleporter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTeleporter_Call) RunAndReturn(run func() ([]byte, error)) *Client_GetTeleporter_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields:
func (_m *Client) GetVersion() (*model.VersionResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *model.VersionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.VersionResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.VersionResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VersionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type Client_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *Client_Expecter) GetVersion() *Client_GetVersion_Call {
	return &Client_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *Client_GetVersion_Call) Run(run func()) *Client_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetVersion_Call) Return(_a0 *model.VersionResponse, _a1 error) *Client_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetVersion_Call) RunAndReturn(run func() (*model.VersionResponse, error)) *Client_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// PatchConfig provides a mock function with given fields: patchRequest
func (_m *Client) PatchConfig(patchRequest *model.PatchConfigRequest) error {
	ret := _m.Called(patchRequest)

	if len(ret) == 0 {
		panic("no return value specified for PatchConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.PatchConfigRequest) error); ok {
		r0 = rf(patchRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_PatchConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchConfig'
type Client_PatchConfig_Call struct {
	*mock.Call
}

// PatchConfig is a helper method to define mock.On call
//   - patchRequest *model.PatchConfigRequest
func (_e *Client_Expecter) PatchConfig(patchRequest interface{}) *Client_PatchConfig_Call {
	return &Client_PatchConfig_Call{Call: _e.mock.On("PatchConfig", patchRequest)}
}

func (_c *Client_PatchConfig_Call) Run(run func(patchRequest *model.PatchConfigRequest)) *Client_PatchConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.PatchConfigRequest))
	})
	return _c
}

func (_c *Client_PatchConfig_Call) Return(_a0 error) *Client_PatchConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_PatchConfig_Call) RunAndReturn(run func(*model.PatchConfigRequest) error) *Client_PatchConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PostAuth provides a mock function with given fields:
func (_m *Client) PostAuth() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PostAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_PostAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAuth'
type Client_PostAuth_Call struct {
	*mock.Call
}

// PostAuth is a helper method to define mock.On call
func (_e *Client_Expecter) PostAuth() *Client_PostAuth_Call {
	return &Client_PostAuth_Call{Call: _e.mock.On("PostAuth")}
}

func (_c *Client_PostAuth_Call) Run(run func()) *Client_PostAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_PostAuth_Call) Return(_a0 error) *Client_PostAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_PostAuth_Call) RunAndReturn(run func() error) *Client_PostAuth_Call {
	_c.Call.Return(run)
	return _c
}

// PostRunGravity provides a mock function with given fields:
func (_m *Client) PostRunGravity() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PostRunGravity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_PostRunGravity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostRunGravity'
type Client_PostRunGravity_Call struct {
	*mock.Call
}

// PostRunGravity is a helper method to define mock.On call
func (_e *Client_Expecter) PostRunGravity() *Client_PostRunGravity_Call {
	return &Client_PostRunGravity_Call{Call: _e.mock.On("PostRunGravity")}
}

func (_c *Client_PostRunGravity_Call) Run(run func()) *Client_PostRunGravity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_PostRunGravity_Call) Return(_a0 error) *Client_PostRunGravity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_PostRunGravity_Call) RunAndReturn(run func() error) *Client_PostRunGravity_Call {
	_c.Call.Return(run)
	return _c
}

// PostTeleporter provides a mock function with given fields: payload, teleporterRequest
func (_m *Client) PostTeleporter(payload []byte, teleporterRequest *model.PostTeleporterRequest) error {
	ret := _m.Called(payload, teleporterRequest)

	if len(ret) == 0 {
		panic("no return value specified for PostTeleporter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, *model.PostTeleporterRequest) error); ok {
		r0 = rf(payload, teleporterRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_PostTeleporter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostTeleporter'
type Client_PostTeleporter_Call struct {
	*mock.Call
}

// PostTeleporter is a helper method to define mock.On call
//   - payload []byte
//   - teleporterRequest *model.PostTeleporterRequest
func (_e *Client_Expecter) PostTeleporter(payload interface{}, teleporterRequest interface{}) *Client_PostTeleporter_Call {
	return &Client_PostTeleporter_Call{Call: _e.mock.On("PostTeleporter", payload, teleporterRequest)}
}

func (_c *Client_PostTeleporter_Call) Run(run func(payload []byte, teleporterRequest *model.PostTeleporterRequest)) *Client_PostTeleporter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(*model.PostTeleporterRequest))
	})
	return _c
}

func (_c *Client_PostTeleporter_Call) Return(_a0 error) *Client_PostTeleporter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_PostTeleporter_Call) RunAndReturn(run func([]byte, *model.PostTeleporterRequest) error) *Client_PostTeleporter_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *Client) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Client_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type Client_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *Client_Expecter) String() *Client_String_Call {
	return &Client_String_Call{Call: _e.mock.On("String")}
}

func (_c *Client_String_Call) Run(run func()) *Client_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_String_Call) Return(_a0 string) *Client_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_String_Call) RunAndReturn(run func() string) *Client_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
